services:
  - type: worker
    name: memeradarbot
    runtime: python
    repo: https://github.com/Damir1974/MemeRadarBot
    branch: main
    plan: free
    envVars:
      - key: API_TOKEN
        value: "8067243807:AAH3xot3O0iEx_c1BSWPwAMrqf-0OZ-lB1w"
      - key: CHAT_ID
        value: "956286581"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
